### ISSUE TITLE
On non-public servers (e.g. localhost), The default user icons are invisible.

### ISSUE THREAD

**Issue by Urushibara** [immewnity/mediawiki-fluent#11]
Gravater icons are available. However, on non-public servers (e.g. localhost), the icons of users who are not registered to Gravater <s>or who are not logged in to the wiki</s> are invisible.
It should be possible to disable the use of the Gravater icons in the LocalSettings.php.

**Comment by redbluegreenhat** [comment]
Should be fixed on https://github.com/immewnity/mediawiki-fluent/pull/15

**Comment by immewnity** [comment]
Yes indeed! #15 is merged in.
