### ISSUE TITLE
Add the ability to change from which CDN Fluent's CSS is downloaded

### ISSUE THREAD

**Issue by redbluegreenhat** [immewnity/mediawiki-fluent#16]
@immewnity, what do you think on making the CDN from which the skin downloads fabric.min.css configurable. Mostly asking because your skin was approved for use on the Miraheze wikifarm (https://phabricator.miraheze.org/T11547), but the hardcoded downloading of CSS from sharepointonline.com (https://github.com/immewnity/mediawiki-fluent/blob/main/Fluent/includes/SkinFluent.php#L28) is a bit of an issue for them, who would rather download from an already approved CDN like jsdelivr. If you approve of this I'd take care of the necessary modifications for this.

**Comment by immewnity** [comment]
Hmm. Is there an issue if the CSS file then downloads files from a different server? The CSS file grabs several fonts and icons from Microsoft's CDN.

I've updated the link to Microsoft's current CDN, office.net, btw - not sure if that makes a difference.

**Comment by redbluegreenhat** [comment]
Normally it wouldn't be an issue, but it is in Miraheze. They use a content security policy that controls from which servers their visitors can download assets, and sharepointonline.com, or even office.net, are not in that list. Adding the ability to configure the CDN is a shortcut meant for use there so that they can skip the CSP review process.

**Comment by immewnity** [comment]
That part I understand, yes. Just... asking the user to provide their own path to a CSS file, rewriting it to also change the paths to each font and icon, isn't great. Perhaps the stylesheet, images, and fonts should be directly included with the skin files?

**Comment by redbluegreenhat** [comment]
It wouldn't be asking the user, I meant adding it as a configuration option in LocalSettings.php, not adding it to Special:Preferences.

And yeah, I think bundling it with the skin would be best.

**Comment by immewnity** [comment]
Ah, by "user" I meant the person setting up each site, not actual end users - should've worded that better. For the short term, I'll grab the files and plop em all in the skin. Future task can be to whittle it down to just what the skin uses.

**Comment by immewnity** [comment]
Fixed in commit 331d9a6
