### ISSUE TITLE
add translation ja

### ISSUE THREAD

**Issue by LZMAShili** [immewnity/mediawiki-fluent#7]
add ja.json (issue create by vscode)
add README-ja.md

**Comment by LZMAShili** [comment]
[ja.json](https://github.com/immewnity/mediawiki-fluent/files/13386284/ja.json)

**Comment by LZMAShili** [comment]
[README-ja.md](https://github.com/immewnity/mediawiki-fluent/files/13386328/README-ja.md)

**Comment by immewnity** [comment]
Added in #8 - thank you!
